/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/snippets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Snippets */
    get: operations["list_snippets_api_snippets_get"];
    put?: never;
    /** Create Snippet */
    post: operations["create_snippet_api_snippets_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/snippets/{snippet_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Snippet */
    get: operations["get_snippet_api_snippets__snippet_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/snippets/{snippet_id}/reviews": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Review History */
    get: operations["review_history_api_snippets__snippet_id__reviews_get"];
    put?: never;
    /** Start Review */
    post: operations["start_review_api_snippets__snippet_id__reviews_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/reviews/{review_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Review Detail */
    get: operations["review_detail_api_reviews__review_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/findings/{finding_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Finding */
    patch: operations["update_finding_api_findings__finding_id__patch"];
    trace?: never;
  };
  "/api/findings/{finding_id}/discussion": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Discussion Detail */
    get: operations["discussion_detail_api_findings__finding_id__discussion_get"];
    put?: never;
    /** Start Discussion */
    post: operations["start_discussion_api_findings__finding_id__discussion_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/findings/{finding_id}/conversations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** New Conversation */
    post: operations["new_conversation_api_findings__finding_id__conversations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/discussion-turns/{turn_id}/retry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Retry Discussion */
    post: operations["retry_discussion_api_discussion_turns__turn_id__retry_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/quality/catalog": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Catalog */
    get: operations["catalog_api_quality_catalog_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/quality/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Session */
    post: operations["create_session_api_quality_sessions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/quality/sessions/{session_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Session */
    get: operations["read_session_api_quality_sessions__session_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/quality/sessions/{session_id}/cases/{case_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Save */
    put: operations["save_api_quality_sessions__session_id__cases__case_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/quality/sessions/{session_id}/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export */
    get: operations["export_api_quality_sessions__session_id__export_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AnnotationInput */
    AnnotationInput: {
      /** Revision */
      revision: number;
      /**
       * Status
       * @default draft
       * @enum {string}
       */
      status: "draft" | "completed";
      /**
       * Independentverdict
       * @default pending
       * @enum {string}
       */
      independentVerdict: "pending" | "issue_found" | "no_issue" | "uncertain";
      /**
       * Contractclarity
       * @default pending
       * @enum {string}
       */
      contractClarity: "pending" | "sufficient" | "missing" | "uncertain";
      /**
       * Referencereason
       * @default pending
       * @enum {string}
       */
      referenceReason:
        | "pending"
        | "supported"
        | "false_positive"
        | "missing_issue"
        | "wrong_details"
        | "missing_context"
        | "needs_verification";
      /**
       * Independentnotes
       * @default
       */
      independentNotes: string;
      /**
       * Contractnotes
       * @default
       */
      contractNotes: string;
      /**
       * Referenceverdict
       * @default pending
       * @enum {string}
       */
      referenceVerdict: "pending" | "approved" | "needs_changes" | "uncertain";
      /**
       * Referencenotes
       * @default
       */
      referenceNotes: string;
      /**
       * Proposedreference
       * @default
       */
      proposedReference: string;
      /** Findings */
      findings?: components["schemas"]["FindingAnnotation"][];
      /** Coverage */
      coverage?: components["schemas"]["CoverageAnnotation"][];
    };
    /** Catalog */
    Catalog: {
      /** Sources */
      sources: components["schemas"]["SourceInfo"][];
      /** Sessions */
      sessions: components["schemas"]["SessionInfo"][];
      /** Unavailable */
      unavailable: string[];
    };
    /**
     * Category
     * @enum {string}
     */
    Category: "bug" | "style" | "performance" | "security";
    /** CoverageAnnotation */
    CoverageAnnotation: {
      /** Runindex */
      runIndex: number;
      /**
       * Verdict
       * @default pending
       * @enum {string}
       */
      verdict: "pending" | "complete" | "missed" | "uncertain" | "failed";
      /**
       * Notes
       * @default
       */
      notes: string;
    };
    /** CreateConversation */
    CreateConversation: {
      /**
       * Clientrequestid
       * Format: uuid
       */
      clientRequestId: string;
    };
    /** CreateDiscussionTurn */
    CreateDiscussionTurn: {
      /** Conversationid */
      conversationId?: string | null;
      /** Message */
      message: string;
      /**
       * Clientrequestid
       * Format: uuid
       */
      clientRequestId: string;
    };
    /** CreateSnippet */
    CreateSnippet: {
      /** Title */
      title: string;
      /** Language */
      language: string;
      /** Code */
      code: string;
    };
    /** DiscussionConversation */
    DiscussionConversation: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Findingid
       * Format: uuid
       */
      findingId: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
    };
    /** DiscussionDetail */
    DiscussionDetail: {
      /**
       * Conversationid
       * Format: uuid
       */
      conversationId: string;
      /** Conversations */
      conversations: components["schemas"]["DiscussionConversation"][];
      /** Hasactivereply */
      hasActiveReply: boolean;
      /** Turns */
      turns: components["schemas"]["DiscussionTurn"][];
    };
    /** DiscussionTurn */
    DiscussionTurn: {
      status: components["schemas"]["ReviewStatus"];
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Startedat */
      startedAt?: string | null;
      /** Finishedat */
      finishedAt?: string | null;
      /** Error */
      error?: string | null;
      /**
       * Conversationid
       * Format: uuid
       */
      conversationId: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Findingid
       * Format: uuid
       */
      findingId: string;
      /**
       * Clientrequestid
       * Format: uuid
       */
      clientRequestId: string;
      /** Usermessage */
      userMessage: string;
      /** Assistantmessage */
      assistantMessage?: string | null;
      /** Attempt */
      attempt: number;
    };
    /** ErrorBody */
    ErrorBody: {
      /** Code */
      code: string;
      /** Message */
      message: string;
    };
    /** ErrorResponse */
    ErrorResponse: {
      error: components["schemas"]["ErrorBody"];
    };
    /** Finding */
    Finding: {
      /** Startline */
      startLine: number;
      /** Endline */
      endLine: number;
      severity: components["schemas"]["Severity"];
      category: components["schemas"]["Category"];
      /** Description */
      description: string;
      /** Suggestedfix */
      suggestedFix?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Reviewrunid
       * Format: uuid
       */
      reviewRunId: string;
      /** @default open */
      resolution: components["schemas"]["Resolution"];
    };
    /** FindingAnnotation */
    FindingAnnotation: {
      /** Runindex */
      runIndex: number;
      /** Findingindex */
      findingIndex: number;
      /**
       * Verdict
       * @default pending
       * @enum {string}
       */
      verdict: "pending" | "correct" | "incorrect" | "uncertain" | "duplicate";
      /**
       * Reason
       * @default pending
       * @enum {string}
       */
      reason:
        | "pending"
        | "supported"
        | "unsupported_assumption"
        | "contradicts_code"
        | "not_actionable"
        | "duplicate"
        | "missing_context"
        | "needs_verification";
      /**
       * Location
       * @default pending
       * @enum {string}
       */
      location: "pending" | "good" | "problem" | "uncertain" | "not_applicable";
      /**
       * Severity
       * @default pending
       * @enum {string}
       */
      severity: "pending" | "good" | "problem" | "uncertain" | "not_applicable";
      /**
       * Fix
       * @default pending
       * @enum {string}
       */
      fix: "pending" | "good" | "problem" | "uncertain" | "not_applicable";
      /**
       * Notes
       * @default
       */
      notes: string;
    };
    /** FindingContent */
    FindingContent: {
      /** Startline */
      startLine: number;
      /** Endline */
      endLine: number;
      severity: components["schemas"]["Severity"];
      category: components["schemas"]["Category"];
      /** Description */
      description: string;
      /** Suggestedfix */
      suggestedFix?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @default ok
       * @constant
       */
      status: "ok";
      /**
       * Database
       * @default connected
       * @constant
       */
      database: "connected";
    };
    /** NewSession */
    NewSession: {
      /** Sourceid */
      sourceId: string;
      /** Reviewer */
      reviewer: string;
    };
    /** QualityCase */
    QualityCase: {
      /** Id */
      id: string;
      /** Language */
      language: string;
      /** Code */
      code: string;
      /** Expected */
      expected: {
        [key: string]: unknown;
      }[];
      /** Notes */
      notes: string;
      /** Runs */
      runs: components["schemas"]["QualityRun"][];
    };
    /** QualityRun */
    QualityRun: {
      /** Index */
      index: number;
      /** Repeat */
      repeat: number;
      /**
       * Status
       * @enum {string}
       */
      status: "succeeded" | "failed";
      /** Findings */
      findings: components["schemas"]["FindingContent"][];
      /** Errortype */
      errorType?: string | null;
    };
    /**
     * Resolution
     * @enum {string}
     */
    Resolution: "open" | "accepted" | "dismissed";
    /** RetryDiscussionTurn */
    RetryDiscussionTurn: {
      /** Attempt */
      attempt: number;
    };
    /** ReviewDetail */
    ReviewDetail: {
      review: components["schemas"]["ReviewRun"];
      /** Findings */
      findings: components["schemas"]["Finding"][];
    };
    /** ReviewHistory */
    ReviewHistory: {
      /** Reviews */
      reviews: components["schemas"]["ReviewRun"][];
    };
    /** ReviewRun */
    ReviewRun: {
      status: components["schemas"]["ReviewStatus"];
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Startedat */
      startedAt?: string | null;
      /** Finishedat */
      finishedAt?: string | null;
      /** Error */
      error?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Snippetid
       * Format: uuid
       */
      snippetId: string;
    };
    /**
     * ReviewStatus
     * @enum {string}
     */
    ReviewStatus: "queued" | "running" | "succeeded" | "failed";
    /** SavedAnnotation */
    SavedAnnotation: {
      /** Revision */
      revision: number;
      /**
       * Status
       * @default draft
       * @enum {string}
       */
      status: "draft" | "completed";
      /**
       * Independentverdict
       * @default pending
       * @enum {string}
       */
      independentVerdict: "pending" | "issue_found" | "no_issue" | "uncertain";
      /**
       * Contractclarity
       * @default pending
       * @enum {string}
       */
      contractClarity: "pending" | "sufficient" | "missing" | "uncertain";
      /**
       * Referencereason
       * @default pending
       * @enum {string}
       */
      referenceReason:
        | "pending"
        | "supported"
        | "false_positive"
        | "missing_issue"
        | "wrong_details"
        | "missing_context"
        | "needs_verification";
      /**
       * Independentnotes
       * @default
       */
      independentNotes: string;
      /**
       * Contractnotes
       * @default
       */
      contractNotes: string;
      /**
       * Referenceverdict
       * @default pending
       * @enum {string}
       */
      referenceVerdict: "pending" | "approved" | "needs_changes" | "uncertain";
      /**
       * Referencenotes
       * @default
       */
      referenceNotes: string;
      /**
       * Proposedreference
       * @default
       */
      proposedReference: string;
      /** Findings */
      findings?: components["schemas"]["FindingAnnotation"][];
      /** Coverage */
      coverage?: components["schemas"]["CoverageAnnotation"][];
      /** Savedat */
      savedAt: string;
    };
    /** SessionDetail */
    SessionDetail: {
      /** Id */
      id: string;
      /** Reviewer */
      reviewer: string;
      /** Createdat */
      createdAt: string;
      source: components["schemas"]["SourceInfo"];
      /** Datasetsha256 */
      datasetSha256: string;
      /** Reportsha256 */
      reportSha256: string;
      /** Cases */
      cases: components["schemas"]["QualityCase"][];
      /** Annotations */
      annotations: {
        [key: string]: components["schemas"]["SavedAnnotation"];
      };
    };
    /** SessionInfo */
    SessionInfo: {
      /** Id */
      id: string;
      /** Reviewer */
      reviewer: string;
      /** Label */
      label: string;
      /** Createdat */
      createdAt: string;
      /** Completed */
      completed: number;
      /** Total */
      total: number;
    };
    /**
     * Severity
     * @enum {string}
     */
    Severity: "critical" | "warning" | "info";
    /** Snippet */
    Snippet: {
      /** Title */
      title: string;
      /** Language */
      language: string;
      /** Code */
      code: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
    };
    /** SnippetDetail */
    SnippetDetail: {
      snippet: components["schemas"]["Snippet"];
      latestReview: components["schemas"]["ReviewRun"] | null;
    };
    /** SnippetList */
    SnippetList: {
      /** Snippets */
      snippets: components["schemas"]["SnippetSummary"][];
      /** Languages */
      languages: string[];
    };
    /** SnippetSummary */
    SnippetSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Title */
      title: string;
      /** Language */
      language: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /**
       * Reviewstatus
       * @enum {string}
       */
      reviewStatus: "not_reviewed" | "in_progress" | "reviewed" | "failed";
    };
    /** SourceInfo */
    SourceInfo: {
      /** Id */
      id: string;
      /** Label */
      label: string;
      /** Model */
      model: string;
      /** Promptversion */
      promptVersion: string;
      /** Casecount */
      caseCount: number;
      /** Runcount */
      runCount: number;
    };
    /** UpdateFinding */
    UpdateFinding: {
      resolution: components["schemas"]["Resolution"];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  list_snippets_api_snippets_get: {
    parameters: {
      query?: {
        language?: string | null;
        reviewStatus?:
          ("not_reviewed" | "in_progress" | "reviewed" | "failed") | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SnippetList"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_snippet_api_snippets_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSnippet"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Snippet"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_snippet_api_snippets__snippet_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        snippet_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SnippetDetail"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  review_history_api_snippets__snippet_id__reviews_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        snippet_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewHistory"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_review_api_snippets__snippet_id__reviews_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        snippet_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewRun"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  review_detail_api_reviews__review_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        review_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewDetail"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_finding_api_findings__finding_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        finding_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateFinding"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Finding"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  discussion_detail_api_findings__finding_id__discussion_get: {
    parameters: {
      query?: {
        conversationId?: string | null;
      };
      header?: never;
      path: {
        finding_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DiscussionDetail"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_discussion_api_findings__finding_id__discussion_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        finding_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDiscussionTurn"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DiscussionTurn"];
        };
      };
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DiscussionTurn"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  new_conversation_api_findings__finding_id__conversations_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        finding_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateConversation"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DiscussionConversation"];
        };
      };
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DiscussionConversation"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  retry_discussion_api_discussion_turns__turn_id__retry_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        turn_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RetryDiscussionTurn"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DiscussionTurn"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  catalog_api_quality_catalog_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Catalog"];
        };
      };
    };
  };
  create_session_api_quality_sessions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewSession"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_session_api_quality_sessions__session_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  save_api_quality_sessions__session_id__cases__case_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
        case_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnnotationInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedAnnotation"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  export_api_quality_sessions__session_id__export_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
