/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/snippets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Snippets */
    get: operations["list_snippets_api_snippets_get"];
    put?: never;
    /** Create Snippet */
    post: operations["create_snippet_api_snippets_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/snippets/{snippet_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Snippet */
    get: operations["get_snippet_api_snippets__snippet_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** CreateSnippet */
    CreateSnippet: {
      /** Title */
      title: string;
      /** Language */
      language: string;
      /** Code */
      code: string;
    };
    /** ErrorBody */
    ErrorBody: {
      /** Code */
      code: string;
      /** Message */
      message: string;
    };
    /** ErrorResponse */
    ErrorResponse: {
      error: components["schemas"]["ErrorBody"];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @default ok
       * @constant
       */
      status: "ok";
      /**
       * Database
       * @default connected
       * @constant
       */
      database: "connected";
    };
    /** ReviewRun */
    ReviewRun: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Snippetid
       * Format: uuid
       */
      snippetId: string;
      status: components["schemas"]["ReviewStatus"];
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Startedat */
      startedAt?: string | null;
      /** Finishedat */
      finishedAt?: string | null;
      /** Error */
      error?: string | null;
    };
    /**
     * ReviewStatus
     * @enum {string}
     */
    ReviewStatus: "queued" | "running" | "succeeded" | "failed";
    /** Snippet */
    Snippet: {
      /** Title */
      title: string;
      /** Language */
      language: string;
      /** Code */
      code: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
    };
    /** SnippetDetail */
    SnippetDetail: {
      snippet: components["schemas"]["Snippet"];
      latestReview: components["schemas"]["ReviewRun"] | null;
    };
    /** SnippetList */
    SnippetList: {
      /** Snippets */
      snippets: components["schemas"]["SnippetSummary"][];
      /** Languages */
      languages: string[];
    };
    /** SnippetSummary */
    SnippetSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Title */
      title: string;
      /** Language */
      language: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /**
       * Reviewstatus
       * @enum {string}
       */
      reviewStatus: "not_reviewed" | "in_progress" | "reviewed" | "failed";
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  list_snippets_api_snippets_get: {
    parameters: {
      query?: {
        language?: string | null;
        reviewStatus?:
          ("not_reviewed" | "in_progress" | "reviewed" | "failed") | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SnippetList"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_snippet_api_snippets_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSnippet"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Snippet"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_snippet_api_snippets__snippet_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        snippet_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SnippetDetail"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
