/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/snippets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Snippets */
    get: operations["list_snippets_api_snippets_get"];
    put?: never;
    /** Create Snippet */
    post: operations["create_snippet_api_snippets_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/snippets/{snippet_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Snippet */
    get: operations["get_snippet_api_snippets__snippet_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/snippets/{snippet_id}/reviews": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start Review */
    post: operations["start_review_api_snippets__snippet_id__reviews_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/reviews/{review_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Review Detail */
    get: operations["review_detail_api_reviews__review_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/findings/{finding_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Finding */
    patch: operations["update_finding_api_findings__finding_id__patch"];
    trace?: never;
  };
  "/api/findings/{finding_id}/discussion": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Discussion Detail */
    get: operations["discussion_detail_api_findings__finding_id__discussion_get"];
    put?: never;
    /** Start Discussion */
    post: operations["start_discussion_api_findings__finding_id__discussion_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/discussion-turns/{turn_id}/retry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Retry Discussion */
    post: operations["retry_discussion_api_discussion_turns__turn_id__retry_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * Category
     * @enum {string}
     */
    Category: "bug" | "style" | "performance" | "security";
    /** CreateDiscussionTurn */
    CreateDiscussionTurn: {
      /** Message */
      message: string;
      /**
       * Clientrequestid
       * Format: uuid
       */
      clientRequestId: string;
    };
    /** CreateSnippet */
    CreateSnippet: {
      /** Title */
      title: string;
      /** Language */
      language: string;
      /** Code */
      code: string;
    };
    /** DiscussionDetail */
    DiscussionDetail: {
      /** Turns */
      turns: components["schemas"]["DiscussionTurn"][];
    };
    /** DiscussionTurn */
    DiscussionTurn: {
      status: components["schemas"]["ReviewStatus"];
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Startedat */
      startedAt?: string | null;
      /** Finishedat */
      finishedAt?: string | null;
      /** Error */
      error?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Findingid
       * Format: uuid
       */
      findingId: string;
      /**
       * Clientrequestid
       * Format: uuid
       */
      clientRequestId: string;
      /** Usermessage */
      userMessage: string;
      /** Assistantmessage */
      assistantMessage?: string | null;
      /** Attempt */
      attempt: number;
    };
    /** ErrorBody */
    ErrorBody: {
      /** Code */
      code: string;
      /** Message */
      message: string;
    };
    /** ErrorResponse */
    ErrorResponse: {
      error: components["schemas"]["ErrorBody"];
    };
    /** Finding */
    Finding: {
      /** Startline */
      startLine: number;
      /** Endline */
      endLine: number;
      severity: components["schemas"]["Severity"];
      category: components["schemas"]["Category"];
      /** Description */
      description: string;
      /** Suggestedfix */
      suggestedFix?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Reviewrunid
       * Format: uuid
       */
      reviewRunId: string;
      /** @default open */
      resolution: components["schemas"]["Resolution"];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @default ok
       * @constant
       */
      status: "ok";
      /**
       * Database
       * @default connected
       * @constant
       */
      database: "connected";
    };
    /**
     * Resolution
     * @enum {string}
     */
    Resolution: "open" | "accepted" | "dismissed";
    /** RetryDiscussionTurn */
    RetryDiscussionTurn: {
      /** Attempt */
      attempt: number;
    };
    /** ReviewDetail */
    ReviewDetail: {
      review: components["schemas"]["ReviewRun"];
      /** Findings */
      findings: components["schemas"]["Finding"][];
    };
    /** ReviewRun */
    ReviewRun: {
      status: components["schemas"]["ReviewStatus"];
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Startedat */
      startedAt?: string | null;
      /** Finishedat */
      finishedAt?: string | null;
      /** Error */
      error?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Snippetid
       * Format: uuid
       */
      snippetId: string;
    };
    /**
     * ReviewStatus
     * @enum {string}
     */
    ReviewStatus: "queued" | "running" | "succeeded" | "failed";
    /**
     * Severity
     * @enum {string}
     */
    Severity: "critical" | "warning" | "info";
    /** Snippet */
    Snippet: {
      /** Title */
      title: string;
      /** Language */
      language: string;
      /** Code */
      code: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
    };
    /** SnippetDetail */
    SnippetDetail: {
      snippet: components["schemas"]["Snippet"];
      latestReview: components["schemas"]["ReviewRun"] | null;
    };
    /** SnippetList */
    SnippetList: {
      /** Snippets */
      snippets: components["schemas"]["SnippetSummary"][];
      /** Languages */
      languages: string[];
    };
    /** SnippetSummary */
    SnippetSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Title */
      title: string;
      /** Language */
      language: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /**
       * Reviewstatus
       * @enum {string}
       */
      reviewStatus: "not_reviewed" | "in_progress" | "reviewed" | "failed";
    };
    /** UpdateFinding */
    UpdateFinding: {
      resolution: components["schemas"]["Resolution"];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  list_snippets_api_snippets_get: {
    parameters: {
      query?: {
        language?: string | null;
        reviewStatus?:
          ("not_reviewed" | "in_progress" | "reviewed" | "failed") | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SnippetList"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_snippet_api_snippets_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSnippet"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Snippet"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_snippet_api_snippets__snippet_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        snippet_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SnippetDetail"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_review_api_snippets__snippet_id__reviews_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        snippet_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewRun"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  review_detail_api_reviews__review_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        review_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewDetail"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_finding_api_findings__finding_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        finding_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateFinding"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Finding"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  discussion_detail_api_findings__finding_id__discussion_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        finding_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DiscussionDetail"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_discussion_api_findings__finding_id__discussion_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        finding_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDiscussionTurn"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DiscussionTurn"];
        };
      };
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DiscussionTurn"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  retry_discussion_api_discussion_turns__turn_id__retry_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        turn_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RetryDiscussionTurn"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DiscussionTurn"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
